spring:
  application:
    name: AuthAudit
  data:
    mongodb:
      uri: mongodb://localhost:27017/auth_audit_db

jwt:
  secret: "tAvw/Sf8UTYCSf8X0WRfDGBSdYyHVHZ5ldeS25pHzEY="
  expiration: 86400000

logging:
  level:
    root: INFO
    com.example.authaudit: DEBUG
